docker exec -it -d grpc-server-1 sh -c ./Run.sh
docker exec -it -d grpc-server-2 sh -c ./Run.sh
docker exec -it -d grpc-server-3 sh -c ./Run.sh
docker exec -it -d grpc-server-4 sh -c ./Run.sh
docker exec -it -d grpc-server-5 sh -c ./Run.sh
docker exec -it -d grpc-server-6 sh -c ./Run.sh
docker exec -it -d grpc-server-7 sh -c ./Run.sh
docker exec -it -d grpc-server-8 sh -c ./Run.sh
docker exec -it -d grpc-server-9 sh -c ./Run.sh
