# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"\x1d\n\x07ModelId\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"Z\n\x0b\x43omponentId\x12!\n\x08model_id\x18\x01 \x01(\x0b\x32\x0f.common.ModelId\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x15\n\rcomponent_idx\x18\x03 \x01(\t\"M\n\tRequestId\x12\x14\n\x0crequester_id\x18\x01 \x01(\t\x12\x13\n\x0brequest_idx\x18\x02 \x01(\x05\x12\x15\n\rcallback_port\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty\"\x8d\x01\n\rOptimizedPlan\x12\x13\n\x0b\x64\x65ployer_id\x18\x01 \x01(\t\x12\x36\n\tplans_map\x18\x02 \x03(\x0b\x32#.common.OptimizedPlan.PlansMapEntry\x1a/\n\rPlansMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIMIZEDPLAN_PLANSMAPENTRY']._loaded_options = None
  _globals['_OPTIMIZEDPLAN_PLANSMAPENTRY']._serialized_options = b'8\001'
  _globals['_MODELID']._serialized_start=24
  _globals['_MODELID']._serialized_end=53
  _globals['_COMPONENTID']._serialized_start=55
  _globals['_COMPONENTID']._serialized_end=145
  _globals['_REQUESTID']._serialized_start=147
  _globals['_REQUESTID']._serialized_end=224
  _globals['_EMPTY']._serialized_start=226
  _globals['_EMPTY']._serialized_end=233
  _globals['_OPTIMIZEDPLAN']._serialized_start=236
  _globals['_OPTIMIZEDPLAN']._serialized_end=377
  _globals['_OPTIMIZEDPLAN_PLANSMAPENTRY']._serialized_start=330
  _globals['_OPTIMIZEDPLAN_PLANSMAPENTRY']._serialized_end=377
# @@protoc_insertion_point(module_scope)
