# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import deployment_pb2 as deployment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in deployment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeploymentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.produce_plan = channel.unary_unary(
                '/pool.Deployment/produce_plan',
                request_serializer=deployment__pb2.ProducePlanRequest.SerializeToString,
                response_deserializer=deployment__pb2.ProducePlanResponse.FromString,
                _registered_method=True)
        self.deploy_plan = channel.unary_unary(
                '/pool.Deployment/deploy_plan',
                request_serializer=deployment__pb2.DeploymentRequest.SerializeToString,
                response_deserializer=deployment__pb2.DeploymentResponse.FromString,
                _registered_method=True)


class DeploymentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def produce_plan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deploy_plan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeploymentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'produce_plan': grpc.unary_unary_rpc_method_handler(
                    servicer.produce_plan,
                    request_deserializer=deployment__pb2.ProducePlanRequest.FromString,
                    response_serializer=deployment__pb2.ProducePlanResponse.SerializeToString,
            ),
            'deploy_plan': grpc.unary_unary_rpc_method_handler(
                    servicer.deploy_plan,
                    request_deserializer=deployment__pb2.DeploymentRequest.FromString,
                    response_serializer=deployment__pb2.DeploymentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pool.Deployment', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pool.Deployment', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Deployment(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def produce_plan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pool.Deployment/produce_plan',
            deployment__pb2.ProducePlanRequest.SerializeToString,
            deployment__pb2.ProducePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deploy_plan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pool.Deployment/deploy_plan',
            deployment__pb2.DeploymentRequest.SerializeToString,
            deployment__pb2.DeploymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
