# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_profile.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model_profile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_profile.proto\x1a\x0c\x63ommon.proto\"k\n\x0eProfileRequest\x12!\n\x08model_id\x18\x01 \x01(\x0b\x32\x0f.common.ModelId\x12\x1f\n\x12profile_regression\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x15\n\x13_profile_regression\"(\n\x0fProfileResponse\x12\x15\n\rmodel_profile\x18\x01 \x01(\t2B\n\x0cModelProfile\x12\x32\n\rprofile_model\x12\x0f.ProfileRequest\x1a\x10.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_profile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILEREQUEST']._serialized_start=37
  _globals['_PROFILEREQUEST']._serialized_end=144
  _globals['_PROFILERESPONSE']._serialized_start=146
  _globals['_PROFILERESPONSE']._serialized_end=186
  _globals['_MODELPROFILE']._serialized_start=188
  _globals['_MODELPROFILE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
