# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_manager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13model_manager.proto\x12\x04pool\x1a\x0c\x63ommon.proto\"3\n\x0eProfileRequest\x12!\n\x08model_id\x18\x01 \x01(\x0b\x32\x0f.common.ModelId\"(\n\x0fProfileResponse\x12\x15\n\rmodel_profile\x18\x01 \x01(\t\"K\n\x10PartitionRequest\x12!\n\x08model_id\x18\x01 \x01(\x0b\x32\x0f.common.ModelId\x12\x14\n\x0csolved_graph\x18\x02 \x01(\t\"\x13\n\x11PartitionResponse2\x8d\x01\n\x0cModelManager\x12<\n\rprofile_model\x12\x14.pool.ProfileRequest\x1a\x15.pool.ProfileResponse\x12?\n\x0c\x64ivide_model\x12\x16.pool.PartitionRequest\x1a\x17.pool.PartitionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROFILEREQUEST']._serialized_start=43
  _globals['_PROFILEREQUEST']._serialized_end=94
  _globals['_PROFILERESPONSE']._serialized_start=96
  _globals['_PROFILERESPONSE']._serialized_end=136
  _globals['_PARTITIONREQUEST']._serialized_start=138
  _globals['_PARTITIONREQUEST']._serialized_end=213
  _globals['_PARTITIONRESPONSE']._serialized_start=215
  _globals['_PARTITIONRESPONSE']._serialized_end=234
  _globals['_MODELMANAGER']._serialized_start=237
  _globals['_MODELMANAGER']._serialized_end=378
# @@protoc_insertion_point(module_scope)
