# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optimizer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'optimizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foptimizer.proto\x12\toptimizer\"\xf4\x01\n\x13OptimizationRequest\x12\x17\n\x0fmodels_profiles\x18\x01 \x03(\t\x12\x17\n\x0fnetwork_profile\x18\x02 \x01(\t\x12\x1e\n\x16\x65xecution_profile_pool\x18\x03 \x01(\t\x12\x16\n\x0elatency_weight\x18\x04 \x01(\x02\x12\x15\n\renergy_weight\x18\x05 \x01(\x02\x12\x19\n\x11\x64\x65vice_max_energy\x18\x06 \x01(\x02\x12\x17\n\x0frequests_number\x18\x07 \x03(\x05\x12\x12\n\nmax_noises\x18\x08 \x03(\x02\x12\x14\n\x0cstart_server\x18\t \x01(\t\".\n\x14OptimizationResponse\x12\x16\n\x0eoptimized_plan\x18\x01 \x01(\t2e\n\x0cOptimization\x12U\n\x12serve_optimization\x12\x1e.optimizer.OptimizationRequest\x1a\x1f.optimizer.OptimizationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIMIZATIONREQUEST']._serialized_start=31
  _globals['_OPTIMIZATIONREQUEST']._serialized_end=275
  _globals['_OPTIMIZATIONRESPONSE']._serialized_start=277
  _globals['_OPTIMIZATIONRESPONSE']._serialized_end=323
  _globals['_OPTIMIZATION']._serialized_start=325
  _globals['_OPTIMIZATION']._serialized_end=426
# @@protoc_insertion_point(module_scope)
