# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import register_pb2 as register__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in register_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegisterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register_server = channel.unary_unary(
                '/register.Register/register_server',
                request_serializer=register__pb2.ReachabilityInfo.SerializeToString,
                response_deserializer=register__pb2.ServerId.FromString,
                _registered_method=True)
        self.get_all_servers_info = channel.unary_unary(
                '/register.Register/get_all_servers_info',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=register__pb2.AllServerInfo.FromString,
                _registered_method=True)
        self.get_info_from_id = channel.unary_unary(
                '/register.Register/get_info_from_id',
                request_serializer=register__pb2.ServerId.SerializeToString,
                response_deserializer=register__pb2.ReachabilityInfo.FromString,
                _registered_method=True)
        self.push_state = channel.unary_unary(
                '/register.Register/push_state',
                request_serializer=register__pb2.ServerState.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.pull_all_states = channel.unary_unary(
                '/register.Register/pull_all_states',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=register__pb2.StateMap.FromString,
                _registered_method=True)


class RegisterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register_server(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_servers_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_info_from_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def push_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pull_all_states(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register_server': grpc.unary_unary_rpc_method_handler(
                    servicer.register_server,
                    request_deserializer=register__pb2.ReachabilityInfo.FromString,
                    response_serializer=register__pb2.ServerId.SerializeToString,
            ),
            'get_all_servers_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_servers_info,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=register__pb2.AllServerInfo.SerializeToString,
            ),
            'get_info_from_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_info_from_id,
                    request_deserializer=register__pb2.ServerId.FromString,
                    response_serializer=register__pb2.ReachabilityInfo.SerializeToString,
            ),
            'push_state': grpc.unary_unary_rpc_method_handler(
                    servicer.push_state,
                    request_deserializer=register__pb2.ServerState.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'pull_all_states': grpc.unary_unary_rpc_method_handler(
                    servicer.pull_all_states,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=register__pb2.StateMap.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'register.Register', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('register.Register', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Register(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register_server(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/register.Register/register_server',
            register__pb2.ReachabilityInfo.SerializeToString,
            register__pb2.ServerId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_all_servers_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/register.Register/get_all_servers_info',
            common__pb2.Empty.SerializeToString,
            register__pb2.AllServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get_info_from_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/register.Register/get_info_from_id',
            register__pb2.ServerId.SerializeToString,
            register__pb2.ReachabilityInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def push_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/register.Register/push_state',
            register__pb2.ServerState.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pull_all_states(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/register.Register/pull_all_states',
            common__pb2.Empty.SerializeToString,
            register__pb2.StateMap.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
