# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import state_pool_pb2 as state__pool__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in state_pool_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatePoolStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.push_state = channel.unary_unary(
                '/pool.StatePool/push_state',
                request_serializer=state__pool__pb2.ServerState.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.pull_all_states = channel.unary_unary(
                '/pool.StatePool/pull_all_states',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=state__pool__pb2.StateMap.FromString,
                _registered_method=True)


class StatePoolServicer(object):
    """Missing associated documentation comment in .proto file."""

    def push_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def pull_all_states(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatePoolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'push_state': grpc.unary_unary_rpc_method_handler(
                    servicer.push_state,
                    request_deserializer=state__pool__pb2.ServerState.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'pull_all_states': grpc.unary_unary_rpc_method_handler(
                    servicer.pull_all_states,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=state__pool__pb2.StateMap.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pool.StatePool', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pool.StatePool', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatePool(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def push_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pool.StatePool/push_state',
            state__pool__pb2.ServerState.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def pull_all_states(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pool.StatePool/pull_all_states',
            common__pb2.Empty.SerializeToString,
            state__pool__pb2.StateMap.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
