# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: state_pool.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'state_pool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10state_pool.proto\x12\x04pool\x1a\x0c\x63ommon.proto\"/\n\x0bServerState\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"l\n\x08StateMap\x12/\n\tstate_map\x18\x01 \x03(\x0b\x32\x1c.pool.StateMap.StateMapEntry\x1a/\n\rStateMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32m\n\tStatePool\x12.\n\npush_state\x12\x11.pool.ServerState\x1a\r.common.Empty\x12\x30\n\x0fpull_all_states\x12\r.common.Empty\x1a\x0e.pool.StateMapb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATEMAP_STATEMAPENTRY']._loaded_options = None
  _globals['_STATEMAP_STATEMAPENTRY']._serialized_options = b'8\001'
  _globals['_SERVERSTATE']._serialized_start=40
  _globals['_SERVERSTATE']._serialized_end=87
  _globals['_STATEMAP']._serialized_start=89
  _globals['_STATEMAP']._serialized_end=197
  _globals['_STATEMAP_STATEMAPENTRY']._serialized_start=150
  _globals['_STATEMAP_STATEMAPENTRY']._serialized_end=197
  _globals['_STATEPOOL']._serialized_start=199
  _globals['_STATEPOOL']._serialized_end=308
# @@protoc_insertion_point(module_scope)
