# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: frontend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'frontend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66rontend.proto\x12\x06server\x1a\x0c\x63ommon.proto\"M\n\rInferenceInfo\x12!\n\x08model_id\x18\x01 \x01(\x0b\x32\x0f.common.ModelId\x12\x19\n\x11input_files_paths\x18\x02 \x03(\t\"P\n\x0fInferenceReturn\x12!\n\x08model_id\x18\x01 \x01(\x0b\x32\x0f.common.ModelId\x12\x1a\n\x12output_files_paths\x18\x02 \x03(\t\"t\n\x0c\x43\x61llbackInfo\x12!\n\x08model_id\x18\x01 \x01(\x0b\x32\x0f.common.ModelId\x12%\n\nrequest_id\x18\x02 \x01(\x0b\x32\x11.common.RequestId\x12\x1a\n\x12output_files_paths\x18\x03 \x03(\t2\x85\x01\n\x08\x46rontEnd\x12\x41\n\x0fstart_inference\x12\x15.server.InferenceInfo\x1a\x17.server.InferenceReturn\x12\x36\n\x0fresult_callback\x12\x14.server.CallbackInfo\x1a\r.common.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frontend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEINFO']._serialized_start=40
  _globals['_INFERENCEINFO']._serialized_end=117
  _globals['_INFERENCERETURN']._serialized_start=119
  _globals['_INFERENCERETURN']._serialized_end=199
  _globals['_CALLBACKINFO']._serialized_start=201
  _globals['_CALLBACKINFO']._serialized_end=317
  _globals['_FRONTEND']._serialized_start=320
  _globals['_FRONTEND']._serialized_end=453
# @@protoc_insertion_point(module_scope)
