# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: registry.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\"\x07\n\x05\x45mpty\"1\n\tLayerInfo\x12\x11\n\tmodelName\x18\x01 \x01(\t\x12\x11\n\tlayerName\x18\x02 \x01(\t\"T\n\rLayerPosition\x12\x1d\n\tlayerInfo\x18\x01 \x01(\x0b\x32\n.LayerInfo\x12\x11\n\tlayerHost\x18\x02 \x01(\t\x12\x11\n\tlayerPort\x18\x03 \x01(\x05\"\x1a\n\x05Model\x12\x11\n\tmodelName\x18\x01 \x01(\t2\x92\x01\n\x08Register\x12)\n\rregisterModel\x12\x06.Model\x1a\x0e.LayerPosition\"\x00\x12)\n\rregisterLayer\x12\x0e.LayerPosition\x1a\x06.Empty\"\x00\x12\x30\n\x10getLayerPosition\x12\n.LayerInfo\x1a\x0e.LayerPosition\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_LAYERINFO']._serialized_start=27
  _globals['_LAYERINFO']._serialized_end=76
  _globals['_LAYERPOSITION']._serialized_start=78
  _globals['_LAYERPOSITION']._serialized_end=162
  _globals['_MODEL']._serialized_start=164
  _globals['_MODEL']._serialized_end=190
  _globals['_REGISTER']._serialized_start=193
  _globals['_REGISTER']._serialized_end=339
# @@protoc_insertion_point(module_scope)
