# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import registry_pb2 as registry__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegisterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerServer = channel.unary_unary(
                '/Register/registerServer',
                request_serializer=registry__pb2.ServerInfo.SerializeToString,
                response_deserializer=registry__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.getLayerPosition = channel.unary_unary(
                '/Register/getLayerPosition',
                request_serializer=registry__pb2.LayerInfo.SerializeToString,
                response_deserializer=registry__pb2.ServerInfo.FromString,
                _registered_method=True)


class RegisterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registerServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLayerPosition(self, request, context):
        """rpc registerLayer(LayerPosition) returns (Empty) ;

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerServer': grpc.unary_unary_rpc_method_handler(
                    servicer.registerServer,
                    request_deserializer=registry__pb2.ServerInfo.FromString,
                    response_serializer=registry__pb2.RegisterResponse.SerializeToString,
            ),
            'getLayerPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.getLayerPosition,
                    request_deserializer=registry__pb2.LayerInfo.FromString,
                    response_serializer=registry__pb2.ServerInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Register', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Register', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Register(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registerServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Register/registerServer',
            registry__pb2.ServerInfo.SerializeToString,
            registry__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getLayerPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Register/getLayerPosition',
            registry__pb2.LayerInfo.SerializeToString,
            registry__pb2.ServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
