# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assignee.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'assignee.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61ssignee.proto\x12\x05\x66\x65tch\x1a\x0c\x63ommon.proto\"U\n\x04Plan\x12&\n\x0b\x61ssignments\x18\x01 \x03(\x0b\x32\x11.fetch.ModelBlock\x12%\n\x0b\x62lock_edges\x18\x02 \x03(\x0b\x32\x10.fetch.BlockEdge\"H\n\nModelBlock\x12&\n\x08\x62lock_id\x18\x01 \x01(\x0b\x32\x14.common.ModelBlockId\x12\x12\n\nis_only_io\x18\x04 \x01(\x08\"~\n\tBlockEdge\x12,\n\x0e\x66irst_block_id\x18\x01 \x01(\x0b\x32\x14.common.ModelBlockId\x12-\n\x0fsecond_block_id\x18\x02 \x01(\x0b\x32\x14.common.ModelBlockId\x12\x14\n\x0coutput_names\x18\x03 \x03(\t\"\x0e\n\x0cSendResponse29\n\x08\x41ssignee\x12-\n\tsend_plan\x12\x0b.fetch.Plan\x1a\x13.fetch.SendResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assignee_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLAN']._serialized_start=39
  _globals['_PLAN']._serialized_end=124
  _globals['_MODELBLOCK']._serialized_start=126
  _globals['_MODELBLOCK']._serialized_end=198
  _globals['_BLOCKEDGE']._serialized_start=200
  _globals['_BLOCKEDGE']._serialized_end=326
  _globals['_SENDRESPONSE']._serialized_start=328
  _globals['_SENDRESPONSE']._serialized_end=342
  _globals['_ASSIGNEE']._serialized_start=344
  _globals['_ASSIGNEE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
