# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\"L\n\x10InferenceRequest\x12\x1a\n\x04info\x18\x01 \x01(\x0b\x32\x0c.server.Info\x12\x1c\n\x06inputs\x18\x02 \x03(\x0b\x32\x0c.server.Data\"?\n\x04\x44\x61ta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"A\n\x04Info\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\"\x13\n\x11InferenceResponse2O\n\x05Model\x12\x46\n\rserve_request\x12\x18.server.InferenceRequest\x1a\x19.server.InferenceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFERENCEREQUEST']._serialized_start=24
  _globals['_INFERENCEREQUEST']._serialized_end=100
  _globals['_DATA']._serialized_start=102
  _globals['_DATA']._serialized_end=165
  _globals['_INFO']._serialized_start=167
  _globals['_INFO']._serialized_end=232
  _globals['_INFERENCERESPONSE']._serialized_start=234
  _globals['_INFERENCERESPONSE']._serialized_end=253
  _globals['_MODEL']._serialized_start=255
  _globals['_MODEL']._serialized_end=334
# @@protoc_insertion_point(module_scope)
