# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import optimizer_pb2 as optimizer__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in optimizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OptimizationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.serve_optimization = channel.stream_unary(
                '/Optimization/serve_optimization',
                request_serializer=optimizer__pb2.OptimizationRequest.SerializeToString,
                response_deserializer=optimizer__pb2.OptimizationResponse.FromString,
                _registered_method=True)
        self.send_model = channel.stream_unary(
                '/Optimization/send_model',
                request_serializer=optimizer__pb2.ModelChunk.SerializeToString,
                response_deserializer=optimizer__pb2.ModelSendResponse.FromString,
                _registered_method=True)


class OptimizationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def serve_optimization(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send_model(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OptimizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'serve_optimization': grpc.stream_unary_rpc_method_handler(
                    servicer.serve_optimization,
                    request_deserializer=optimizer__pb2.OptimizationRequest.FromString,
                    response_serializer=optimizer__pb2.OptimizationResponse.SerializeToString,
            ),
            'send_model': grpc.stream_unary_rpc_method_handler(
                    servicer.send_model,
                    request_deserializer=optimizer__pb2.ModelChunk.FromString,
                    response_serializer=optimizer__pb2.ModelSendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Optimization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Optimization', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Optimization(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def serve_optimization(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Optimization/serve_optimization',
            optimizer__pb2.OptimizationRequest.SerializeToString,
            optimizer__pb2.OptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def send_model(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Optimization/send_model',
            optimizer__pb2.ModelChunk.SerializeToString,
            optimizer__pb2.ModelSendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
