# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optimizer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'optimizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foptimizer.proto\"B\n\x13OptimizationRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x17\n\x0finference_shape\x18\x02 \x03(\x05\"^\n\x14OptimizationResponse\x12%\n\x0b\x61ssignments\x18\x01 \x03(\x0b\x32\x10.ModelAssignment\x12\x1f\n\x0bnext_blocks\x18\x02 \x03(\x0b\x32\n.BlockNext\"6\n\x0fModelAssignment\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x11\n\tserver_id\x18\x02 \x01(\t\"I\n\tBlockNext\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x13\n\x0boutput_name\x18\x02 \x01(\t\x12\x15\n\rnext_block_id\x18\x03 \x01(\t\"V\n\nModelChunk\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\nmodel_size\x18\x02 \x01(\x05\x12\x11\n\tchunk_idx\x18\x03 \x01(\x05\x12\r\n\x05\x63hunk\x18\x04 \x01(\x0c\"\x13\n\x11ModelSendResponse2\x84\x01\n\x0cOptimization\x12\x43\n\x12serve_optimization\x12\x14.OptimizationRequest\x1a\x15.OptimizationResponse(\x01\x12/\n\nsend_model\x12\x0b.ModelChunk\x1a\x12.ModelSendResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'optimizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPTIMIZATIONREQUEST']._serialized_start=19
  _globals['_OPTIMIZATIONREQUEST']._serialized_end=85
  _globals['_OPTIMIZATIONRESPONSE']._serialized_start=87
  _globals['_OPTIMIZATIONRESPONSE']._serialized_end=181
  _globals['_MODELASSIGNMENT']._serialized_start=183
  _globals['_MODELASSIGNMENT']._serialized_end=237
  _globals['_BLOCKNEXT']._serialized_start=239
  _globals['_BLOCKNEXT']._serialized_end=312
  _globals['_MODELCHUNK']._serialized_start=314
  _globals['_MODELCHUNK']._serialized_end=400
  _globals['_MODELSENDRESPONSE']._serialized_start=402
  _globals['_MODELSENDRESPONSE']._serialized_end=421
  _globals['_OPTIMIZATION']._serialized_start=424
  _globals['_OPTIMIZATION']._serialized_end=556
# @@protoc_insertion_point(module_scope)
