# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pool.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npool.proto\x12\x04pool\x1a\x0c\x63ommon.proto\"I\n\nModelChunk\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x05\x12\x11\n\tchunk_idx\x18\x03 \x01(\x05\x12\x12\n\nchunk_data\x18\x04 \x01(\x0c\"b\n\x0bPushRequest\x12,\n\x0emodel_block_id\x18\x01 \x01(\x0b\x32\x14.common.ModelBlockId\x12%\n\x0bmodel_chunk\x18\x02 \x01(\x0b\x32\x10.pool.ModelChunk\"\x0e\n\x0cPushResponse\";\n\x0bPullRequest\x12,\n\x0emodel_block_id\x18\x01 \x01(\x0b\x32\x14.common.ModelBlockId\"5\n\x0cPullResponse\x12%\n\x0bmodel_chunk\x18\x01 \x01(\x0b\x32\x10.pool.ModelChunk2y\n\tModelPool\x12\x35\n\npush_model\x12\x11.pool.PushRequest\x1a\x12.pool.PushResponse(\x01\x12\x35\n\npull_model\x12\x11.pool.PullRequest\x1a\x12.pool.PullResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELCHUNK']._serialized_start=34
  _globals['_MODELCHUNK']._serialized_end=107
  _globals['_PUSHREQUEST']._serialized_start=109
  _globals['_PUSHREQUEST']._serialized_end=207
  _globals['_PUSHRESPONSE']._serialized_start=209
  _globals['_PUSHRESPONSE']._serialized_end=223
  _globals['_PULLREQUEST']._serialized_start=225
  _globals['_PULLREQUEST']._serialized_end=284
  _globals['_PULLRESPONSE']._serialized_start=286
  _globals['_PULLRESPONSE']._serialized_end=339
  _globals['_MODELPOOL']._serialized_start=341
  _globals['_MODELPOOL']._serialized_end=462
# @@protoc_insertion_point(module_scope)
