# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\x1a\x0c\x63ommon.proto\"\x14\n\x12\x41ssignmentResponse\"q\n\nModelInput\x12,\n\x0emodel_block_id\x18\x01 \x01(\x0b\x32\x14.common.ModelBlockId\x12$\n\x0cinput_tensor\x18\x02 \x01(\x0b\x32\x0e.server.Tensor\x12\x0f\n\x07is_last\x18\x03 \x01(\x08\"N\n\x06Tensor\x12 \n\x04info\x18\x01 \x01(\x0b\x32\x12.server.TensorInfo\x12\"\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x13.server.TensorChunk\"7\n\nTensorInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05shape\x18\x03 \x03(\x05\"B\n\x0bTensorChunk\x12\x12\n\ntotal_size\x18\x01 \x01(\x05\x12\x11\n\tchunk_idx\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"\x13\n\x11SendInputResponse2L\n\tInference\x12?\n\nsend_input\x12\x12.server.ModelInput\x1a\x19.server.SendInputResponse\"\x00(\x01\x32J\n\x08\x41ssignee\x12>\n\tsend_plan\x12\x15.common.OptimizedPlan\x1a\x1a.server.AssignmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSIGNMENTRESPONSE']._serialized_start=38
  _globals['_ASSIGNMENTRESPONSE']._serialized_end=58
  _globals['_MODELINPUT']._serialized_start=60
  _globals['_MODELINPUT']._serialized_end=173
  _globals['_TENSOR']._serialized_start=175
  _globals['_TENSOR']._serialized_end=253
  _globals['_TENSORINFO']._serialized_start=255
  _globals['_TENSORINFO']._serialized_end=310
  _globals['_TENSORCHUNK']._serialized_start=312
  _globals['_TENSORCHUNK']._serialized_end=378
  _globals['_SENDINPUTRESPONSE']._serialized_start=380
  _globals['_SENDINPUTRESPONSE']._serialized_end=399
  _globals['_INFERENCE']._serialized_start=401
  _globals['_INFERENCE']._serialized_end=477
  _globals['_ASSIGNEE']._serialized_start=479
  _globals['_ASSIGNEE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
