networks:
  dissertation_network:
    driver: bridge
    name: dissertation_network

services:
  optimizer:
    build:
      dockerfile: ./docker/optimizer.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Optimizer:/src/Optimizer

      - ./Main/OptimizerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./Common:/src/Common
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonIds:/src/CommonIds

      - ./Other/models_profiles:/optimizer_data/models_profiles
      - ./Other/plans/:/optimizer_data/plans
      - ./Other/cplex_installer.bin:/root/cplex_installer.bin
    working_dir: /src

  deployer:
    build:
      dockerfile: ./docker/deployer.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Deployer:/src/Deployer

      - ./Main/DeployerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./Common:/src/Common
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonIds:/src/CommonIds
    working_dir: /src

  registry:
    build:
      dockerfile: ./docker/registry.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Registry:/src/Registry

      - ./Main/RegistryMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./CommonServer:/src/CommonServer
      - ./Common:/src/Common
      - ./CommonModel:/src/CommonModel
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonIds:/src/CommonIds
      - ./CommonQuantization:/src/CommonQuantization
    working_dir: /src

  server:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Server:/src/Server

      - ./Main/ServerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini
      - ./config/energy_config.ini:/src/config/energy_config.ini

      - ./CommonServer:/src/CommonServer
      - ./Common:/src/Common
      - ./CommonModel:/src/CommonModel
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonIds:/src/CommonIds
      - ./CommonQuantization:/src/CommonQuantization

      - ./Other/latency_scripts/delay_script.py:/root/delay_script.py

      - ./Test/Results/Exec_Profile/Edge_yolo11x-seg_1.25_exec_profile.json:/server_data/models_profiles/yolo11x-seg_profile.json
      - ./Test/Results/Exec_Profile/Edge_yolo11m_1.25_exec_profile.json:/server_data/models_profiles/yolo11m_profile.json
    working_dir: /src
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits: # Hard Limit
          cpus: "1.25"

  cloud:
    build:
      dockerfile: ./docker/cloud.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Server:/src/Server

      - ./Main/ServerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini
      - ./config/energy_config.ini:/src/config/energy_config.ini

      - ./CommonServer:/src/CommonServer
      - ./Common:/src/Common
      - ./CommonModel:/src/CommonModel
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonIds:/src/CommonIds
      - ./CommonQuantization:/src/CommonQuantization

      - ./Other/latency_scripts/delay_script.py:/root/delay_script.py

      - ./Test/Results/Exec_Profile/Cloud_yolo11x-seg_0.0_exec_profile.json:/server_data/models_profiles/yolo11x-seg_profile.json
      - ./Test/Results/Exec_Profile/Cloud_yolo11m_0.0_exec_profile.json:/server_data/models_profiles/yolo11m_profile.json
    working_dir: /src
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits: # Hard Limit
          cpus: "1.25"

  client:
    build:
      dockerfile: ./docker/server.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./Client:/src/Client
      - ./Server:/src/Server

      - ./Main/ServerMain.py:/src/ServerMain.py
      - ./Main/ClientMain.py:/src/ClientMain.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini
      - ./config/energy_config.ini:/src/config/energy_config.ini

      - ./CommonServer:/src/CommonServer
      - ./Common:/src/Common
      - ./CommonIds:/src/CommonIds
      - ./CommonModel:/src/CommonModel
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonQuantization:/src/CommonQuantization

      - ./Other/latency_scripts/delay_script.py:/root/delay_script.py

      - ./Test/Results/Exec_Profile/Client_yolo11x-seg_0.75_exec_profile.json:/server_data/models_profiles/yolo11x-seg_profile.json
      - ./Test/Results/Exec_Profile/Client_yolo11m_0.75_exec_profile.json:/server_data/models_profiles/yolo11m_profile.json
    working_dir: /src
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits: # Hard Limit
          cpus: 0.75

  model_manager:
    build:
      dockerfile: ./docker/manager.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./ModelPool:/src/ModelPool
      - ./ModelDivider:/src/ModelDivider
      - ./ModelProfiler:/src/ModelProfiler

      - ./Main/ModelManagerMain.py:/src/Main.py
      - ./start.sh:/src/start.sh
      - ./config/local_config.ini:/src/config/config.ini

      - ./Common:/src/Common
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonModel:/src/CommonModel
      - ./CommonIds:/src/CommonIds
      - ./CommonQuantization:/src/CommonQuantization

      - ./Other/models:/model_pool_data/models
      - ./Other/models_profiles:/model_profiler_data/models_profiles
      - ./Other/divided_models:/model_pool_data/components
      - ./Other/calibration_dataset:/model_pool_data/calibration_dataset

      - ./Test:/src/Test

    working_dir: /src

  test:
    build:
      dockerfile: ./docker/test.dockerfile
    tty: true
    stdin_open: true
    networks:
      - dissertation_network
    volumes:
      - ./proto_compiled:/src/proto_compiled

      - ./config/local_config.ini:/src/config/config.ini

      - ./Test:/src/Test

      - ./Common:/src/Common
      - ./CommonProfile:/src/CommonProfile
      - ./CommonPlan:/src/CommonPlan
      - ./CommonModel:/src/CommonModel
      - ./CommonIds:/src/CommonIds
      - ./CommonQuantization:/src/CommonQuantization

      - ./Test:/src/Test

    working_dir: /src
